services:
  licensemgr:
    image: json-endpoint:latest
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://lm-mathcad.infn.it
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: license
      POSTGRES_PASSWORD: L1c3ns3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

        #  adminer:
        #    image: adminer
        #    restart: always
        #    ports:
        #      - 8080:8080

volumes:
  pgdata:
